general {
  lock_cmd = /home/dragon/.dotfiles/scripts/lock-session.sh
  before_sleep_cmd = /home/dragon/.dotfiles/scripts/lock-session.sh
  after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 min -> bloquear
listener {
  timeout = 300
  on-timeout = /home/dragon/.dotfiles/scripts/lock-session.sh
}

# 10 min -> apagar pantalla
listener {
  timeout = 600
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# 30 min -> suspender
listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
