general {
  grace = 2
}

background {
  color = rgba(0,0,0,0.65)
}

input-field {
  size = 320, 56
  rounding = 14
  outline_thickness = 2
  dots_center = true
  fade_on_empty = false
  placeholder_text = "Password..."
  position = 0, -30
  halign = center
  valign = center
}

label {
  text = $TIME
  font_size = 64
  position = 0, 90
  halign = center
  valign = center
}

