hl.monitor({ output = "WAYLAND-1", disabled = true })
hl.monitor({ output = "eDP-1",     mode = "preferred",     position = "auto",   scale = 1 })
hl.monitor({ output = "DVI-I-1",   mode = "1920x1080@144", position = "0x0",    scale = 1 })
hl.monitor({ output = "DVI-I-2",   mode = "1920x1080@60",  position = "1920x0", scale = 1, transform = 3 })
hl.monitor({ output = "",          mode = "preferred",     position = "auto",   scale = "auto" })
